Notifications dropdown
Sophia-Sergio/spec-atelier-front pull request #40
Opened 2021-12-21 02:17 UTC by akibac

new component for notifications per user

2021-12-23 17:20 UTC, andyOlarte514 commented on src/components/navbar/navbar-notifications/NavNotifications.jsx
> +	return (
return isLogin && (

2021-12-23 17:20 UTC, andyOlarte514 commented on src/components/navbar/navbar-notifications/NavNotifications.jsx
> +	if (isLogin)
delete this

2021-12-23 17:24 UTC, andyOlarte514 commented on src/components/navbar/navbar-notifications/NavNotifications.styles.jsx
> +		right: 52px !important;
delete this `!important`

2021-12-23 17:24 UTC, andyOlarte514 commented on src/components/navbar/navbar-notifications/NavNotifications.styles.jsx
> +		right: 58px !important;
delete this `!important`

2021-12-23 17:27 UTC, andyOlarte514 commented on src/components/navbar/navbar-notifications/NavNotifications.styles.jsx
> +	color: #757575;
use const color

2021-12-23 17:28 UTC, andyOlarte514 commented on src/components/navbar/navbar-notifications/NavNotifications.styles.jsx
> +    color: #fff;
use const color

2021-12-23 17:28 UTC, andyOlarte514 commented on src/components/navbar/navbar-notifications/NavNotifications.styles.jsx
> +	color: #757575;
use const color

2021-12-23 17:29 UTC, andyOlarte514 commented on src/components/notifications/Notification.jsx
> +export default Notifications;
add EOF

2021-12-23 17:31 UTC, andyOlarte514 commented on src/components/notifications/Notifications.styles.jsx
> +	background-color: #c8c8c8;
use const color

2021-12-23 17:31 UTC, andyOlarte514 commented on src/components/notifications/Notifications.styles.jsx
> +		color: #656565;
use const color

2021-12-23 17:31 UTC, andyOlarte514 commented on src/components/notifications/Notifications.styles.jsx
> +    background-color: #31cbb7;
use const color

2021-12-23 17:32 UTC, andyOlarte514 commented on src/components/notifications/Notifications.styles.jsx
> +    color: #fff;
use const color

2021-12-23 17:32 UTC, andyOlarte514 commented on src/components/notifications/Notifications.styles.jsx
> +	color: #757575;
use const color

2021-12-23 17:35 UTC, andyOlarte514 commented on src/containers/auth/auth.actions.js
> +		if (data.action.idNoti !== undefined) {
if(data.action.idNoti) {

2021-12-23 17:35 UTC, andyOlarte514 commented on src/containers/auth/auth.actions.js
> +			if (data.action.idNoti !== undefined) {
same

2021-12-23 17:39 UTC, andyOlarte514 commented on src/containers/projects-list/ProjectsList.actions.js
> +export const accepthNotificationsAC = (body) => async (dispatch) => {
format this

2021-12-23 17:39 UTC, andyOlarte514 commented on src/containers/auth/auth.actions.js
> +export const rejectNotifications = (body) => async (dispatch) => {
format this

2021-12-23 17:39 UTC, andyOlarte514 commented on src/containers/projects-list/ProjectsList.actions.js
> +export const rejectNotificationsAC = (body) => async (dispatch) => {
format this

2021-12-23 20:04 UTC, andyOlarte514 approved these changes

2021-12-23 22:59 UTC, Sophia-Sergio commented
por favor @akibac no alcanzo a revisar más de tu código pero como ya ves encontré varias cosas a cambiar... sigue revisando este tipo de cosas en todo tu código y avísame cuando lo tengas.. si quieres haz nuevos commits para que no tengas que rehacer todo.
Hay harta documentación de React para ir interiorizándote de buenas prácticas en React. Espero que puedas consultar artículos como los que salen acá https://kentcdodds.com/blog?q=react.

@andyOlarte514 te encargo que este PR quede con la calidad esperada siguiendo buenas prácticas de React.

2021-12-23 22:59 UTC, Sophia-Sergio requested changes

2021-12-23 22:59 UTC, Sophia-Sergio commented on .gitignore
> -
por qué estás añadiendo esto?

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/IconUser/index.jsx
> +import React from 'react';
Todo este archivo en realidad lo hizo @andyOlarte514 por qué lo tienes tú @akibac ?

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/IconUser/styles.jsx
> +	background-color: #757575;
no usar colores harcodeados

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/buttons/Button.styles.jsx
> +  border: 2px solid #afafaf;
no usar colores hardcodeados

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/navbar/navbar-notifications/NavNotifications.jsx
> +		item.list.map((detail) =>
no usar map a menos que quieras retornar un arreglo, lo cual no es el caso..

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/navbar/navbar-notifications/NavNotifications.jsx
> +			item.list.map((detail) =>
no usar map a menos que quieras retornar un arreglo, lo cual no es el caso..

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/navbar/navbar-notifications/NavNotifications.jsx
> +			setUdateNot(false);
setUdateNot => setUpdateNot

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/navbar/navbar-notifications/NavNotifications.jsx
> +		const ids2 = [];
hay que usar nombres más semánticos

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/navbar/navbar-notifications/NavNotifications.jsx
> +					{array_news.length+array_total.length === 1 &&(
array_news.length+array_total.length => array_news.length + array_total.length
(favorecer legibilidad del código)

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/navbar/navbar-notifications/NavNotifications.jsx
> +										<Notifications key={d}
por qué no usar el id de la notificación como key?
y por qué se llama notifications con s, si se supone que una sola?
además tienes el nombre `Notification.jsx`, y también `NavNotifications.styles.jsx`

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/navbar/navbar-notifications/NavNotifications.jsx
> +					{array_news.length+array_total.length > 1 &&(
acá repites todo el código? por qué? cámbialo porfa
si solo cambia el height, no veo necesario repetir todo el código

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/navbar/navbar-notifications/NavNotifications.styles.jsx
> +	box-shadow: 0 -1px 4px 0 rgba(0, 0, 0, 0.25), 0 2px 4px 0 rgba(0, 0, 0, 0.25);
no usar colores hardcodeados

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/navbar/navbar-notifications/NavNotifications.styles.jsx
> +	font-weight: normal;
por defecto es normal, por qué lo especificas?

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/navbar/navbar-notifications/NavNotifications.styles.jsx
> +	padding-left: 26px;
preocuparse en todos los archivos de que la identación sea correcta

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/notifications/Notification.jsx
> +
remover línea vacía

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/notifications/Notification.jsx
> +                                <ContentActions>
volver a guardar este archivo completamente, tiene la identación de a 4

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/notifications/Notification.jsx
> +                                                    <ActionPerformed>Proyecto aceptado </ActionPerformed>
código repetido abajo, evitarlo porfa.. si cambias solo los estilos, defínelos en otro lado y luego los usas dependiendo de `loadingNoti`

lo mismo para Proyecto Rechazado.
De hecho deberías separarlo a otro componente, recuerda siempre tu código debe ser DRY.. ese concepto está detrás de usar componentes en react 
https://javascript.plainenglish.io/5-dry-principles-to-follow-in-react-6ca0405986a9

2021-12-23 22:59 UTC, Sophia-Sergio commented on src/components/notifications/Notification.jsx
> +                        <ListItem style={{ backgroundColor: 'none' }}>
esto está muy parecido a otro, haz más componentes por favor que reaccionen a los estados. así le sacas partido a react

2021-12-23 23:00 UTC, Sophia-Sergio requested changes
por favor @akibac no alcanzo a revisar más de tu código pero como ya ves encontré varias cosas a cambiar... sigue revisando este tipo de cosas en todo tu código y avísame cuando lo tengas.. si quieres haz nuevos commits para que no tengas que rehacer todo.
Hay harta documentación de React para ir interiorizándote de buenas prácticas en React. Espero que puedas consultar artículos como los que salen acá https://kentcdodds.com/blog?q=react.

@andyOlarte514 te encargo que este PR quede con la calidad esperada siguiendo buenas prácticas de React.

2021-12-24 02:03 UTC, akibac commented on .gitignore
> -
La carpeta vs code no debe ir detro de los cambios, ya que se agrego con la configuración del tab que hicimos hace dias

2021-12-24 02:07 UTC, akibac commented on src/components/IconUser/index.jsx
> +import React from 'react';
Este componente se agrego porque andy tiene su rama apuntando hacia la epica de permisos por ende en mi rama se necesitaba dicho componente para la funcionalidad completa de la imagen del usuario. igualmente andy aun no hace su merge hacia develop con estos cambios .

2021-12-24 05:10 UTC, Sophia-Sergio commented on src/components/IconUser/index.jsx
> +import React from 'react';
con solo haber salido de la rama de Andy te hubiese funcionado, o haciendo un cherry-pick de su commit a tu rama
https://www.atlassian.com/git/tutorials/cherry-pick

2021-12-27 15:30 UTC, Sophia-Sergio commented on src/components/IconUser/styles.jsx
> +	background-color: #757575;
esto todavía no lo cambias.. revisaste todos mis comentarios?

2021-12-27 15:44 UTC, Sophia-Sergio commented on src/components/navbar/navbar-notifications/NavNotification.styles.jsx
> +	padding-right: 4%;
por qué a veces usas % y otras pixeles?

2021-12-27 15:45 UTC, Sophia-Sergio commented on src/components/notifications/Notification.jsx
> +    const [styleButtonAccept, setStyleButtonAccept] = useState({ marginLeft: '11px', background: 'rgb(156 221 212);', marginTop: '8px' });
color hardcodeado

2021-12-27 15:47 UTC, Sophia-Sergio commented on src/components/notifications/Notification.jsx
> +
por qué línea vacía?

también debería quedar con otra identación todo este archivo, ahora está con 4 espacios, y quedamos de que usaríamos de a 2 espacios

2021-12-27 16:12 UTC, Sophia-Sergio commented on src/services/specs.service.js
> +		{ block: blockID },
por qué está esto en tu PR?

2021-12-31 18:31 UTC, Sophia-Sergio commented on src/components/notifications/Notification.jsx
> +  const [styleButtonAccept, setStyleButtonAccept] = useState({ marginLeft: '11px', background: 'rgb(156 221 212);', marginTop: '8px' });
todos los colores deben ser importados

2021-12-31 18:32 UTC, Sophia-Sergio commented on src/containers/spec-header/SpecHeader.container.jsx
> +<<<<<<< HEAD
se cae el proyecto, favor probar los cambios que existe antes de subir el PR

2021-12-31 18:34 UTC, Sophia-Sergio commented on src/containers/spec-header/SpecHeader.container.jsx
> +<<<<<<< HEAD
eliminar merge comments

2022-01-06 02:16 UTC, Sophia-Sergio commented on src/containers/projects-list/ProjectsList.actions.js
> +			);
por qué estos mensajes están en inglés? es algo que ve el usuario? si es así, en español porfa

2022-01-06 02:31 UTC, Sophia-Sergio commented on src/containers/projects-list/ProjectsList.container.jsx
> +        dispatch(onShowAlertSuccess({ message: 'Not Modified' }));
acá tambiém

2022-01-06 02:37 UTC, Sophia-Sergio commented on src/containers/spec-header/SpecHeader.actions.js
> +export const accepthNotificationsAC = (body) => async (dispatch) => {
mal escrito el nombre, tiene una h entremedio

2022-01-06 03:15 UTC, Sophia-Sergio commented on src/views/Projects.jsx
> +import React from 'react';
extraño.. qué hiciste en este archivo para que todo aparezca como tuyo? cuando la mayoría del código estaba desde antes

2022-01-11 00:03 UTC, Sophia-Sergio commented on src/containers/routes/PrivateRoute.jsx
> +						const array_url = pathname.split('/');
aquí repites código sin necesidad (entre nunca y casi nunca hay necesidad)
debería quedar así:

```js
if (!isLogin) {
  const array_url = pathname.split('/');
  const array_var = search.split('=');
  if(pathname.search("/projects/accept_invitation/") === 0 )
    return <Redirect to={`/login/${array_url[2]}/${array_url[3]}/${array_var[1]}`} />;
  if(pathname.search("/projects/refuse_invitation/") === 0 )
    return <Redirect to={`/projects/${array_url[2]}/${array_url[3]}/${array_var[1]}`} />;
  if(isAutoLogout)
    return <Redirect to="/login" />;
  
}
```

2022-01-11 00:55 UTC, merged