[hito-10] Permissions
Sophia-Sergio/spec-atelier-front pull request #50
Opened 2022-01-22 06:28 UTC by andyOlarte514

- Permissions

- https://app.zeplin.io/project/5b1b2e41d7dcaf956a390a68/screen/612411b9c4981c10bde6c82e

2022-01-22 23:42 UTC, Sophia-Sergio commented
en lo que probé las opciones salen a la derecha (editar y ver), en zeplin salen a la izquierdxa

navegador
![image](https://user-images.githubusercontent.com/20115754/150658958-7bd257d4-867d-4485-9361-8eb2cc8dea74.png)

zeplin
![image](https://user-images.githubusercontent.com/20115754/150658999-d26bc62c-daa8-4fd2-804c-c0695edfdf86.png)

2022-01-23 00:20 UTC, Sophia-Sergio commented
al presionar en la línea debería el mismo comportamiento que cuando aprietas el `carot`

![image](https://user-images.githubusercontent.com/20115754/150659766-da157935-7ba9-414b-bc9d-8ecad01359ba.png)

2022-01-23 01:24 UTC, Sophia-Sergio requested changes
Te dejé varios comentarios, por favor revísalos y dame tu feedback en todos..  buen finde!

2022-01-23 01:24 UTC, Sophia-Sergio commented on src/containers/spec-modal-team/utils.js
> +	usersData.forEach((user) => {
user `.filter`... también tienes código repetido adentro de la función, me parece que lo puedes dejar sin él

2022-01-23 01:24 UTC, Sophia-Sergio commented on src/containers/spec-modal-team/utils.js
> +	return {
no necesitas el return si devuelves todo lo que está dentro del objeto

2022-01-23 01:24 UTC, Sophia-Sergio commented on src/containers/spec-modal-team/utils.js
> +	const selectedSections = [];
deberías poder `.filter` para `selectedSections` y `selectedItems`

2022-01-23 01:24 UTC, Sophia-Sergio commented on src/services/users.service.js
> +				permissionType === PERMISSIONS_TYPE.INVITATION
pasarlo a una función que te devuelva lo que necesitas en vez de repetir código

2022-01-23 01:24 UTC, Sophia-Sergio commented on src/views/Specification.jsx
> +			{!!sections.length && (
innecesario colocar `()` después del `&&`

2022-01-23 01:24 UTC, Sophia-Sergio commented on src/containers/spec-modal-team/components/ProjectInfoShare/index.jsx
> +				if (toggledTwo) {
innecesario los `{}`

2022-01-23 01:24 UTC, Sophia-Sergio commented on src/containers/spec-modal-team/components/ProjectInfoShare/index.jsx
> +				if (isAllSelected(node)) {
innecesario `{}`

2022-01-24 21:23 UTC, andyOlarte514 commented on src/components/IconUser/styles.jsx
>  	display: flex;
en este caso mira de volver a hacer la prueba porque como comentaste las saque y rompio el componente
![image](https://user-images.githubusercontent.com/40371687/150867222-ec4f41bd-40e3-44c3-b57e-4cc443e4f755.png)

2022-01-24 21:25 UTC, andyOlarte514 commented on src/components/basics/SelectorRelative.jsx
>  				{!options.length && <NoOptions>No hay Opciones Disponibles</NoOptions>}
hice el cambio pero hay que tener en cuenta que esto no es un cambio que agregue o que saque, es algo que ya estaba en el componente de hace tiempo, igual ya hice la correccion

2022-01-24 21:26 UTC, andyOlarte514 commented on src/components/basics/SelectorRelative.styles.jsx
>  export const Option = styled.section`
esto al igual que el anterior no es desarrollo hecho por mi, los cambios mios github los marca en verde, este ya estaba desde antes al igual que el anterior hare la correccion pero que no sea un bloqueante para mi hito en un futuro esto por fa

2022-01-24 21:28 UTC, andyOlarte514 commented on src/components/basics/SelectorRelative.styles.jsx
>  export const Option = styled.section`
los cambios mios en este archivo fueron 
`	display: flex;
	justify-content: space-between;`

2022-01-24 21:29 UTC, andyOlarte514 commented on src/components/basics/SelectorRelative.styles.jsx
>  		background-color: #eee;
este tampoco es un cambio agregado por mi, lo cambiare igualmente aunque probablemente genere conflicto con los cambios de Nelida en los colores

2022-01-24 21:32 UTC, andyOlarte514 commented on src/components/basics/SelectorRelative.styles.jsx
> +	font-family: Lato;
asi se ve cuando le quito el `font-family: Lato`
![image](https://user-images.githubusercontent.com/40371687/150868349-05fe90d2-082b-4b29-a4c5-5647864763c8.png)

asi se ve con la font definida
![image](https://user-images.githubusercontent.com/40371687/150868395-aef25405-b77e-4633-af98-6ef7a3dc7d38.png)

2022-01-24 21:37 UTC, andyOlarte514 commented on src/containers/spec-modal-team/components/ProjectInfoShare/components/CheckItem/index.jsx
> +/* eslint-disable import/no-cycle */
por lo general es para no tener redundancia a la hora de nombramiento de archivos y carpetas por ejemplo si tengo una carpeta en este caso `CheckItem` ya es entendible que el `index.jsx` es el archivo principal de este componente el volver a poner `CheckItem.jsx` es algo redundante e implica que al momento de hacer un import de este componete deba hacerse `import CheckItem from CheckItem/CheckItem.jsx` si solo lo nombro `index.jsx` al momento de importar seria `import Check
Item from CheckItem;`

2022-01-25 03:42 UTC, Sophia-Sergio commented on src/components/basics/SelectorRelative.jsx
>  				{!options.length && <NoOptions>No hay Opciones Disponibles</NoOptions>}
gracias!

2022-01-25 03:43 UTC, Sophia-Sergio commented on src/components/IconUser/styles.jsx
>  	display: flex;
se quedan entonces.. debo haber visto mal

2022-01-25 03:44 UTC, Sophia-Sergio commented on src/components/basics/SelectorRelative.styles.jsx
>  export const Option = styled.section`
tienes razón, pesques si ya estaba de antes

2022-01-25 03:44 UTC, Sophia-Sergio commented on src/components/basics/SelectorRelative.styles.jsx
>  		background-color: #eee;
para evitar los conflicto deberías rebasear develop

2022-02-02 02:13 UTC, Sophia-Sergio commented
al cambiar el permiso de un miembro del equipo se reordenan, deberían quedar en el mismo orden que venía por primera vez
![image](https://user-images.githubusercontent.com/20115754/152082750-d835a074-050d-4418-a04b-680127ae891c.png)
![image](https://user-images.githubusercontent.com/20115754/152082774-ee5a1ed2-1f1a-4306-9b5b-59f82f6ce34b.png)

2022-02-02 02:17 UTC, Sophia-Sergio commented
al cambiar el permiso dentro de un miembro del equipo, se mueve el texto.. al parecer el texto se mueve porque el tamaño de ver es menor a editar.. hay que colocarle un tamaño fijo igual al largo del texto editar a ese div para que no suceda.
![image](https://user-images.githubusercontent.com/20115754/152082948-4c3d3d80-3bfc-43da-a91c-80daedf11e64.png)
![image](https://user-images.githubusercontent.com/20115754/152083007-20f3c97b-b74d-4668-9afd-2ea6971a2db8.png)

2022-02-02 02:20 UTC, Sophia-Sergio commented
está llamando al endpoint para ver si existe aunque no haya cambiado el texto, solo por salirme del input
![image](https://user-images.githubusercontent.com/20115754/152083348-f998f7b0-06d9-471f-8a71-52b012320ad6.png)

2022-02-02 02:23 UTC, Sophia-Sergio commented
en el modal "invita a tu equipo al proyecto" las opciones están a la derecha, deberían estar a la izquierda como ya lo haces en las otros modales

![image](https://user-images.githubusercontent.com/20115754/152083554-55469133-39d2-4f12-a4f1-5b4c6798c3b1.png)

2022-02-02 02:31 UTC, Sophia-Sergio commented
Al sumar a otro miembro al equipo, según el diseño deberían aparecer en los íconos de usuario, los que ya están añadidos.. para que el usuario tenga el contexto para tomar la decisión. 
![image](https://user-images.githubusercontent.com/20115754/152084281-b5d80fc3-5301-4539-9da5-20c34a8da762.png)

deberías usar el mismo componente que usas cuando muestras las partidas compartidas a un usuario
![image](https://user-images.githubusercontent.com/20115754/152084330-8fbf5757-fd43-4906-afc7-f77091328029.png)


diseño: https://specatelier.invisionapp.com/console/share/CZ1407IRHJ/757162517

2022-02-02 02:34 UTC, Sophia-Sergio commented
puedo colocar guardar y envía una petición para updatear los permisos o invitaciones.. pero no hice ni un cambio ,no debería enviar nada.. de hecho el botón guardar debería estar deshabilitado a menos que haga algún cambio que necesite ser guardado

![image](https://user-images.githubusercontent.com/20115754/152084566-cea074e0-67dd-4b51-ab81-e45bfc159589.png)

2022-02-02 02:36 UTC, Sophia-Sergio commented
después de añadir un miembro al equipo hace una llamada al endpoint de project_specs.. por qué? si no es necesario, no hace la llamada
![image](https://user-images.githubusercontent.com/20115754/152084729-c2af2165-b4c9-4e9e-994e-71343a03ca4a.png)

2022-02-02 02:41 UTC, Sophia-Sergio commented
añadí una nueva sección a la ET (Terminación) pero no sale en el modal de equipo
![image](https://user-images.githubusercontent.com/20115754/152084991-484bb1a0-df8b-4f6a-85f7-bcce9f23124d.png)
![image](https://user-images.githubusercontent.com/20115754/152085010-fe82684c-9916-41b5-a4b4-f0846623c0ae.png)

tuve que recargar y apareció
![image](https://user-images.githubusercontent.com/20115754/152085038-6ec66db5-b8d4-49a4-b864-5be9700b128e.png)

2022-02-02 03:07 UTC, Sophia-Sergio commented
traté de correrlo con el back en local, el proyecto tiene `team: []` y no funciona cuando hago click en "Equipo"

2022-02-06 23:16 UTC, andyOlarte514 commented
> Al sumar a otro miembro al equipo, según el diseño deberían aparecer los íconos de usuario, los que ya están añadidos.. para que el usuario tenga el contexto para tomar la decisión. ![image](https://user-images.githubusercontent.com/20115754/152084281-b5d80fc3-5301-4539-9da5-20c34a8da762.png)
> 
> deberías usar el mismo componente que usas cuando muestras las partidas compartidas a un usuario ![image](https://user-images.githubusercontent.com/20115754/152084330-8fbf5757-fd43-4906-afc7-f77091328029.png)
> 
> diseño: https://specatelier.invisionapp.com/console/share/CZ1407IRHJ/757162517

quisiera mas contexto de este caso porque se supone que esto ya esta, no he cambiado nada y al agregar nuevos miembros se muestran los actuales.
![image](https://user-images.githubusercontent.com/40371687/152705658-40cc37da-09d8-4ddc-bbd0-5210553f6b1b.png)

2022-02-07 22:40 UTC, Sophia-Sergio approved these changes
LGTM

2022-02-07 22:40 UTC, merged