Create change history table
Sophia-Sergio/spec-atelier-front pull request #54
Opened 2022-02-18 03:33 UTC by nelidita

Creation of a table to visualize the changes of a project, with a search engine that searches by comments and name, in addition to a filter by author, with a pagination with a limit of 7 changes per page.

2022-03-04 03:31 UTC, Sophia-Sergio requested changes

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/SpecHistory.container.jsx
> +        Cell: ({ row }) => {
no es necesario el `return`, y puedes reemplazar los `{}` por `()`

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/SpecHistory.container.jsx
> +      <ButtonsHistoryChangesManagement />
por qué se llama buttons (en plural)?

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/SpecHistory.styles.js
> +  display:flex;
`display:flex;` => `display: flex;`(falta un espacio)

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/SpecHistory.styles.js
> +    display: 'none'};
por qué con '', los otros no tienen.. es necesario?

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/SpecHistory.styles.js
> +export const SearchFiltersContainer = styled.div`
se debería llamar `SearchFilterContainer` (en singular)

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/SpecHistory.styles.js
> +	width: 100%;
identación

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/SpecHistory.styles.js
> +	position: relative;
identación

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/SpecHistory.styles.js
> +  box-sizing: border-box;
quizás no es necesario

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/SpecHistory.styles.js
> +	padding-left: 8px;
identación

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/SpecHistory.styles.js
> +export const IconAction = styled.img`
ActionIcon.. en inglés el sustantivo va después del adjetivo. Icon sería el sustantivo y Action el adjetivo.

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/SpecHistory.styles.js
> +export const LiPagination = styled.div`
qué es `Li`? mejor colocar la palabra completa para que tu código sea más semántico.

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/SpecHistory.styles.js
> +  padding: 5px;
es necesario padding por todos lados?

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/SpecHistory.styles.js
> +export const NameSection = styled.section`
SectionName

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/components/ButtonsHistoryChangesManagement.jsx
> +        <ItemText active={option_changes_management === SPEC_CHANGE_MANAGEMENT}>Gestión de Cambios</ItemText>
en minúscula "Cambios"
![image](https://user-images.githubusercontent.com/20115754/156693631-ef28ca91-1e0d-48fc-a683-ece031c3ad52.png)

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/components/SearchFilter.jsx
> +          <Label>Filtrar por autor</Label>
si usas este texto acá y en la línea 62 mejor guardarlo en una constante y usar esa variable en ambos lados.

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/containers/spec-history/components/StructureTableChangeHistory.jsx
> +    if (pageIndex > 0) {
si es solo una línea después del if, no tienes para qué usar `{}` (revisar en otros lados si pasa lo mismo)

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/helpers/custom-hooks.helper.js
> +
línea de más

2022-03-04 03:31 UTC, Sophia-Sergio commented on src/views/Projects.styles.jsx
> +  width: 100%;
cuál es la diferencia?

2022-03-04 15:10 UTC, Sophia-Sergio commented
Revisar que el tamaño del contenedor del historial de cambios no varíe de tamaño dependiendo de la cantidad de cambios
<img width="738" alt="image" src="https://user-images.githubusercontent.com/20115754/156788351-e1581e7c-60b0-49cf-8306-1f43f874002d.png">

2022-03-04 15:11 UTC, Sophia-Sergio commented
Se debería ver solo 10 páginas en el historial de cambios, y aparecer en el medio cuando se supere las 10

2022-03-04 16:36 UTC, nelidita commented on src/components/IconUser/index.jsx
> +          size={size}
Se sustituyó el el `border-radius: ${({ size = 24 }) => `${size / 2}px`};` por `border-radius: 50%;` por lo que se elimina este parametro para este style component ya que es innnecesario, pero se mantiene en el componente IconUser.

2022-03-04 23:44 UTC, nelidita commented on src/components/basics/SelectorRelative.styles.jsx
> +  box-sizing: border-box;
Eliminado de todos los archivos.

2022-03-05 00:06 UTC, nelidita commented on src/containers/spec-history/SpecHistory.container.jsx
> +      <ButtonsHistoryChangesManagement />
Porque es un componente que lleva dos botones, el de Gestion de cambios y el boton de Historial.

2022-03-05 00:20 UTC, nelidita commented on src/containers/spec-history/SpecHistory.styles.js
> +    display: 'none'};
Tienes razón, no es necesario, además habia una llave de más.

2022-03-05 00:25 UTC, nelidita commented on src/containers/spec-history/SpecHistory.styles.js
> +	width: 100%;
Al igual que el otro error de identación, lo tengo bien.

2022-03-05 00:33 UTC, nelidita commented on src/containers/spec-history/SpecHistory.styles.js
> +export const LiPagination = styled.div`
Li son los elementos de una lista que se ordenan dentro de un ul en html.

2022-03-05 00:41 UTC, nelidita commented on src/containers/spec-history/SpecHistory.styles.js
> +  padding: 5px;
elimine el `padding: 5px;` y lo cambie por
  ```
display: inline-flex;
width: 20px;
height: 22px;
justify-content: center;
align-items: center;
```
si te parece mejor.

2022-03-05 16:15 UTC, nelidita commented on src/views/Projects.styles.jsx
> +  width: 100%;
Con 100vw, el container ocupaba más espacio, haciendo que tuviera un scroll horizontal, al cambiarlo a porcentaje ocupó el 100% del ancho de su contenedor haciendo que se ajustara al ancho de la pantalla y eliminando el sroll horizontal.

2022-03-05 17:02 UTC, nelidita commented
> Revisar que el tamaño del contenedor del historial de cambios no varíe de tamaño dependiendo de la cantidad de cambios <img alt="image" width="738" src="https://user-images.githubusercontent.com/20115754/156788351-e1581e7c-60b0-49cf-8306-1f43f874002d.png">

2022-03-07 14:43 UTC, Sophia-Sergio commented on src/views/Projects.styles.jsx
> +  width: 100%;
genial!

2022-04-04 03:00 UTC, andyOlarte514 approved these changes

2022-04-08 03:09 UTC, Sophia-Sergio reviewed
minor comments

2022-04-08 03:09 UTC, Sophia-Sergio commented on src/containers/spec-history/components/StructureTableChangeHistory.jsx
> +    const limitPage = 7;
limitPage => pageLimit

2022-04-08 03:09 UTC, Sophia-Sergio commented on src/containers/spec-products/SpecProducts.container.jsx
> +    selectedItems.forEach(({ section_id }) => {
use filter instead

2022-04-17 21:05 UTC, Sophia-Sergio approved these changes
LGTM

2022-04-17 21:06 UTC, merged